package mainmodel

import list "bushuray-tui/components/List"

var dummy_items []list.ListItem = []list.ListItem{
	{Name: "🚀 @SmoothVPN - D", Protocol: "V-LESS", TestResult: 100},
	{Name: "[🇨🇦]t.me/ConfigsHub", Protocol: "SHADOW", TestResult: 2490},
	{Name: "ids here", Protocol: "V-MESS"},
	{Name: "join here @somerandomid, join here @somerandomid, join here @somerandomid, join here @somerandomid, join here @somerandomid, join here @somerandomid, join here @somerandomid, join here @somerandomid", Protocol: "TROJAN", TestResult: 1200},
	{Name: "50gb config", Protocol: "TROJAN", TestResult: -1},
	{Name: "پروکسی دایمی", Protocol: "SOCKS5", TestResult: -2},
	{Name: "پروکسی دایمی", Protocol: "SOCKS5", TestResult: 1000},
	{Name: "🚀 @SmoothVPN - D", Protocol: "V-LESS", TestResult: 1000},
	{Name: "[🇨🇦]t.me/ConfigsHub", Protocol: "SHADOW", TestResult: 490},
	{Name: "ids here", Protocol: "V-MESS", TestResult: 875},
	{Name: "join here @somerandomid", Protocol: "TROJAN", TestResult: 0},
	{Name: "50gb config", Protocol: "TROJAN", TestResult: 190},
	{Name: "پروکسی دایمی", Protocol: "SOCKS5", TestResult: -1},
	{Name: "🚀 @SmoothVPN - D", Protocol: "V-LESS", TestResult: -1},
	{Name: "[🇨🇦]t.me/ConfigsHub", Protocol: "SHADOW", TestResult: -2},
	{Name: "🚀 @SmoothVPN - D", Protocol: "V-LESS", TestResult: 100},
	{Name: "[🇨🇦]t.me/ConfigsHub", Protocol: "SHADOW", TestResult: 2490},
	{Name: "ids here", Protocol: "V-MESS"},
	{Name: "join here @somerandomid", Protocol: "TROJAN", TestResult: 0},
	{Name: "50gb config", Protocol: "TROJAN", TestResult: -1},
	{Name: "پروکسی دایمی", Protocol: "SOCKS5", TestResult: -2},
	{Name: "🚀 @SmoothVPN - D", Protocol: "V-LESS", TestResult: 1000},
	{Name: "[🇨🇦]t.me/ConfigsHub", Protocol: "SHADOW", TestResult: 490},
	{Name: "ids here", Protocol: "V-MESS", TestResult: 875},
	{Name: "join here @somerandomid", Protocol: "TROJAN", TestResult: 0},
	{Name: "50gb config", Protocol: "TROJAN", TestResult: 190},
	{Name: "پروکسی دایمی", Protocol: "SOCKS5", TestResult: -1},
	{Name: "🚀 @SmoothVPN - D", Protocol: "V-LESS", TestResult: -1},
	{Name: "[🇨🇦]t.me/ConfigsHub", Protocol: "SHADOW", TestResult: -2},
	{Name: "🚀 @SmoothVPN - D", Protocol: "V-LESS"},
	{Name: "[🇨🇦]t.me/ConfigsHub", Protocol: "SHADOW"},
	{Name: "ids here", Protocol: "V-MESS"},
	{Name: "join here @somerandomid", Protocol: "TROJAN"},
	{Name: "50gb config", Protocol: "TROJAN"},
	{Name: "پروکسی دایمی", Protocol: "SOCKS5"},
	{Name: "🚀 @SmoothVPN - D", Protocol: "V-LESS"},
	{Name: "[🇨🇦]t.me/ConfigsHub", Protocol: "SHADOW"},
	{Name: "ids here", Protocol: "V-MESS"},
	{Name: "join here @somerandomid", Protocol: "TROJAN"},
	{Name: "50gb config", Protocol: "TROJAN"},
	{Name: "پروکسی دایمی", Protocol: "SOCKS5"},
	{Name: "🚀 @SmoothVPN - D", Protocol: "V-LESS", TestResult: 100},
	{Name: "[🇨🇦]t.me/ConfigsHub", Protocol: "SHADOW", TestResult: 2490},
	{Name: "ids here", Protocol: "V-MESS"},
	{Name: "join here @somerandomid, join here @somerandomid, join here @somerandomid, join here @somerandomid, join here @somerandomid, join here @somerandomid, join here @somerandomid, join here @somerandomid", Protocol: "TROJAN", TestResult: 1200},
	{Name: "50gb config", Protocol: "TROJAN", TestResult: -1},
	{Name: "پروکسی دایمی", Protocol: "SOCKS5", TestResult: -2},
	{Name: "🚀 @SmoothVPN - D", Protocol: "V-LESS", TestResult: 1000},
	{Name: "[🇨🇦]t.me/ConfigsHub", Protocol: "SHADOW", TestResult: 490},
	{Name: "ids here", Protocol: "V-MESS", TestResult: 875},
	{Name: "join here @somerandomid", Protocol: "TROJAN", TestResult: 0},
	{Name: "50gb config", Protocol: "TROJAN", TestResult: 190},
	{Name: "پروکسی دایمی", Protocol: "SOCKS5", TestResult: -1},
	{Name: "🚀 @SmoothVPN - D", Protocol: "V-LESS", TestResult: -1},
	{Name: "[🇨🇦]t.me/ConfigsHub", Protocol: "SHADOW", TestResult: -2},
	{Name: "🚀 @SmoothVPN - D", Protocol: "V-LESS", TestResult: 100},
	{Name: "[🇨🇦]t.me/ConfigsHub", Protocol: "SHADOW", TestResult: 2490},
	{Name: "ids here", Protocol: "V-MESS"},
	{Name: "join here @somerandomid", Protocol: "TROJAN", TestResult: 0},
	{Name: "50gb config", Protocol: "TROJAN", TestResult: -1},
	{Name: "پروکسی دایمی", Protocol: "SOCKS5", TestResult: -2},
	{Name: "🚀 @SmoothVPN - D", Protocol: "V-LESS", TestResult: 1000},
	{Name: "[🇨🇦]t.me/ConfigsHub", Protocol: "SHADOW", TestResult: 490},
	{Name: "ids here", Protocol: "V-MESS", TestResult: 875},
	{Name: "join here @somerandomid", Protocol: "TROJAN", TestResult: 0},
	{Name: "50gb config", Protocol: "TROJAN", TestResult: 190},
	{Name: "پروکسی دایمی", Protocol: "SOCKS5", TestResult: -1},
	{Name: "🚀 @SmoothVPN - D", Protocol: "V-LESS", TestResult: -1},
	{Name: "[🇨🇦]t.me/ConfigsHub", Protocol: "SHADOW", TestResult: -2},
	{Name: "🚀 @SmoothVPN - D", Protocol: "V-LESS"},
	{Name: "[🇨🇦]t.me/ConfigsHub", Protocol: "SHADOW"},
	{Name: "ids here", Protocol: "V-MESS"},
	{Name: "join here @somerandomid", Protocol: "TROJAN"},
	{Name: "50gb config", Protocol: "TROJAN"},
	{Name: "پروکسی دایمی", Protocol: "SOCKS5"},
	{Name: "🚀 @SmoothVPN - D", Protocol: "V-LESS"},
	{Name: "[🇨🇦]t.me/ConfigsHub", Protocol: "SHADOW"},
	{Name: "ids here", Protocol: "V-MESS"},
	{Name: "join here @somerandomid", Protocol: "TROJAN"},
	{Name: "50gb config", Protocol: "TROJAN"},
	{Name: "پروکسی دایمی", Protocol: "SOCKS5"},
}

func dummyItemsWithPrefix(prefix string) []list.ListItem {
	var dummywp []list.ListItem = make([]list.ListItem, len(dummy_items))
	// copy(dummy_items, dummywp)
	for i := range dummy_items {
		dummywp[i].Name = prefix + "-" + dummy_items[i].Name
		dummywp[i].Protocol = dummy_items[i].Protocol
		dummywp[i].TestResult = dummy_items[i].TestResult
	}
	return dummywp
}
